/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BlogSitemapDotxmlRouteImport } from './routes/blog-sitemap[.]xml'
import { Route as ExtensionRouteImport } from './routes/extension'
import { Route as HelpRouteImport } from './routes/help'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as WhatsNewRouteImport } from './routes/whats-new'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ApiAnalyticsRouteImport } from './routes/api/analytics'
import { Route as ApiDictionaryRouteImport } from './routes/api/dictionary'
import { Route as ApiErrorsRouteImport } from './routes/api/errors'
import { Route as ApiGutenbergRouteImport } from './routes/api/gutenberg'
import { Route as ApiOpdsRouteImport } from './routes/api/opds'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminBlogIndexRouteImport } from './routes/admin.blog.index'
import { Route as AdminBlogIdRouteImport } from './routes/admin.blog.$id'
import { Route as ApiGutendexSplatRouteImport } from './routes/api/gutendex.$'
import { Route as ApiOpenlibrarySplatRouteImport } from './routes/api/openlibrary.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSitemapDotxmlRoute = BlogSitemapDotxmlRouteImport.update({
  id: '/blog-sitemap.xml',
  path: '/blog-sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionRoute = ExtensionRouteImport.update({
  id: '/extension',
  path: '/extension',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsNewRoute = WhatsNewRouteImport.update({
  id: '/whats-new',
  path: '/whats-new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAnalyticsRoute = ApiAnalyticsRouteImport.update({
  id: '/api/analytics',
  path: '/api/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDictionaryRoute = ApiDictionaryRouteImport.update({
  id: '/api/dictionary',
  path: '/api/dictionary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiErrorsRoute = ApiErrorsRouteImport.update({
  id: '/api/errors',
  path: '/api/errors',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGutenbergRoute = ApiGutenbergRouteImport.update({
  id: '/api/gutenberg',
  path: '/api/gutenberg',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpdsRoute = ApiOpdsRouteImport.update({
  id: '/api/opds',
  path: '/api/opds',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogIndexRoute = AdminBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogIdRoute = AdminBlogIdRouteImport.update({
  id: '/blog/$id',
  path: '/blog/$id',
  getParentRoute: () => AdminRoute,
} as any)
const ApiGutendexSplatRoute = ApiGutendexSplatRouteImport.update({
  id: '/api/gutendex/$',
  path: '/api/gutendex/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenlibrarySplatRoute = ApiOpenlibrarySplatRouteImport.update({
  id: '/api/openlibrary/$',
  path: '/api/openlibrary/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog-sitemap.xml': typeof BlogSitemapDotxmlRoute
  '/extension': typeof ExtensionRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/whats-new': typeof WhatsNewRoute
  '/api/analytics': typeof ApiAnalyticsRoute
  '/api/dictionary': typeof ApiDictionaryRoute
  '/api/errors': typeof ApiErrorsRoute
  '/api/gutenberg': typeof ApiGutenbergRoute
  '/api/opds': typeof ApiOpdsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/api/gutendex/$': typeof ApiGutendexSplatRoute
  '/api/openlibrary/$': typeof ApiOpenlibrarySplatRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/account': typeof AccountRoute
  '/blog-sitemap.xml': typeof BlogSitemapDotxmlRoute
  '/extension': typeof ExtensionRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/whats-new': typeof WhatsNewRoute
  '/api/analytics': typeof ApiAnalyticsRoute
  '/api/dictionary': typeof ApiDictionaryRoute
  '/api/errors': typeof ApiErrorsRoute
  '/api/gutenberg': typeof ApiGutenbergRoute
  '/api/opds': typeof ApiOpdsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/api/gutendex/$': typeof ApiGutendexSplatRoute
  '/api/openlibrary/$': typeof ApiOpenlibrarySplatRoute
  '/admin/blog': typeof AdminBlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog-sitemap.xml': typeof BlogSitemapDotxmlRoute
  '/extension': typeof ExtensionRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/whats-new': typeof WhatsNewRoute
  '/api/analytics': typeof ApiAnalyticsRoute
  '/api/dictionary': typeof ApiDictionaryRoute
  '/api/errors': typeof ApiErrorsRoute
  '/api/gutenberg': typeof ApiGutenbergRoute
  '/api/opds': typeof ApiOpdsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/api/gutendex/$': typeof ApiGutendexSplatRoute
  '/api/openlibrary/$': typeof ApiOpenlibrarySplatRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessibility'
    | '/account'
    | '/admin'
    | '/blog-sitemap.xml'
    | '/extension'
    | '/help'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/support'
    | '/terms'
    | '/thank-you'
    | '/whats-new'
    | '/api/analytics'
    | '/api/dictionary'
    | '/api/errors'
    | '/api/gutenberg'
    | '/api/opds'
    | '/blog/$slug'
    | '/admin/'
    | '/blog/'
    | '/admin/blog/$id'
    | '/api/gutendex/$'
    | '/api/openlibrary/$'
    | '/admin/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessibility'
    | '/account'
    | '/blog-sitemap.xml'
    | '/extension'
    | '/help'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/support'
    | '/terms'
    | '/thank-you'
    | '/whats-new'
    | '/api/analytics'
    | '/api/dictionary'
    | '/api/errors'
    | '/api/gutenberg'
    | '/api/opds'
    | '/blog/$slug'
    | '/admin'
    | '/blog'
    | '/admin/blog/$id'
    | '/api/gutendex/$'
    | '/api/openlibrary/$'
    | '/admin/blog'
  id:
    | '__root__'
    | '/'
    | '/accessibility'
    | '/account'
    | '/admin'
    | '/blog-sitemap.xml'
    | '/extension'
    | '/help'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/support'
    | '/terms'
    | '/thank-you'
    | '/whats-new'
    | '/api/analytics'
    | '/api/dictionary'
    | '/api/errors'
    | '/api/gutenberg'
    | '/api/opds'
    | '/blog/$slug'
    | '/admin/'
    | '/blog/'
    | '/admin/blog/$id'
    | '/api/gutendex/$'
    | '/api/openlibrary/$'
    | '/admin/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessibilityRoute: typeof AccessibilityRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogSitemapDotxmlRoute: typeof BlogSitemapDotxmlRoute
  ExtensionRoute: typeof ExtensionRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  ThankYouRoute: typeof ThankYouRoute
  WhatsNewRoute: typeof WhatsNewRoute
  ApiAnalyticsRoute: typeof ApiAnalyticsRoute
  ApiDictionaryRoute: typeof ApiDictionaryRoute
  ApiErrorsRoute: typeof ApiErrorsRoute
  ApiGutenbergRoute: typeof ApiGutenbergRoute
  ApiOpdsRoute: typeof ApiOpdsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiGutendexSplatRoute: typeof ApiGutendexSplatRoute
  ApiOpenlibrarySplatRoute: typeof ApiOpenlibrarySplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog-sitemap.xml': {
      id: '/blog-sitemap.xml'
      path: '/blog-sitemap.xml'
      fullPath: '/blog-sitemap.xml'
      preLoaderRoute: typeof BlogSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extension': {
      id: '/extension'
      path: '/extension'
      fullPath: '/extension'
      preLoaderRoute: typeof ExtensionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whats-new': {
      id: '/whats-new'
      path: '/whats-new'
      fullPath: '/whats-new'
      preLoaderRoute: typeof WhatsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/analytics': {
      id: '/api/analytics'
      path: '/api/analytics'
      fullPath: '/api/analytics'
      preLoaderRoute: typeof ApiAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dictionary': {
      id: '/api/dictionary'
      path: '/api/dictionary'
      fullPath: '/api/dictionary'
      preLoaderRoute: typeof ApiDictionaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/errors': {
      id: '/api/errors'
      path: '/api/errors'
      fullPath: '/api/errors'
      preLoaderRoute: typeof ApiErrorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gutenberg': {
      id: '/api/gutenberg'
      path: '/api/gutenberg'
      fullPath: '/api/gutenberg'
      preLoaderRoute: typeof ApiGutenbergRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/opds': {
      id: '/api/opds'
      path: '/api/opds'
      fullPath: '/api/opds'
      preLoaderRoute: typeof ApiOpdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog/': {
      id: '/admin/blog/'
      path: '/blog'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AdminBlogIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog/$id': {
      id: '/admin/blog/$id'
      path: '/blog/$id'
      fullPath: '/admin/blog/$id'
      preLoaderRoute: typeof AdminBlogIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/gutendex/$': {
      id: '/api/gutendex/$'
      path: '/api/gutendex/$'
      fullPath: '/api/gutendex/$'
      preLoaderRoute: typeof ApiGutendexSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openlibrary/$': {
      id: '/api/openlibrary/$'
      path: '/api/openlibrary/$'
      fullPath: '/api/openlibrary/$'
      preLoaderRoute: typeof ApiOpenlibrarySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBlogIdRoute: typeof AdminBlogIdRoute
  AdminBlogIndexRoute: typeof AdminBlogIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminBlogIdRoute: AdminBlogIdRoute,
  AdminBlogIndexRoute: AdminBlogIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessibilityRoute: AccessibilityRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogSitemapDotxmlRoute: BlogSitemapDotxmlRoute,
  ExtensionRoute: ExtensionRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  ThankYouRoute: ThankYouRoute,
  WhatsNewRoute: WhatsNewRoute,
  ApiAnalyticsRoute: ApiAnalyticsRoute,
  ApiDictionaryRoute: ApiDictionaryRoute,
  ApiErrorsRoute: ApiErrorsRoute,
  ApiGutenbergRoute: ApiGutenbergRoute,
  ApiOpdsRoute: ApiOpdsRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiGutendexSplatRoute: ApiGutendexSplatRoute,
  ApiOpenlibrarySplatRoute: ApiOpenlibrarySplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
